name: CI

on:
  push:
    branches: [ main, docker_build ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.12
          architecture: x64

      - name: Install poetry
        run: pip install poetry && poetry config virtualenvs.create false
      - name: Install python packages
        run: poetry install -v

      - name: Run Tests
        run: make test
      - name: Linter
        run: make linter
      - name: build container
        run: make build
